name: nox with uv

on:
  push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  uv-nox:
    name: uv-nox 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run nox
        # the nox sessions here are small, thus we glob them together;
        # TODO: split across matrix that nox already knows: https://nox.thea.codes/en/stable/cookbook.html#generating-a-matrix-with-github-actions
        run: uv run nox