name: nox with uv

on:
  push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  uv-nox:
    name: uv-nox 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run nox
        # the nox sessions here are small, thus we glob them together;
        # TODO: split across matrix that nox already knows: https://nox.thea.codes/en/stable/cookbook.html#generating-a-matrix-with-github-actions
        run: uv run nox