name: nox with uv

on:
  push:
    #branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  uv-nox:
    name: uv-nox 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install nox
        run: pip install nox

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run nox
        run: python -m nox --session tests-${{ matrix.python-version }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}