name: Publish to PyPI

on:
  push:
  workflow_dispatch:

jobs:
  upload_pypi:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pyotc/
    permissions:
      id-token: write    
    # if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    # if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v5
        with:
          pattern: uv-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
        # To test uploads to TestPyPI, uncomment the following:
        with:
          repository-url: https://test.pypi.org/legacy/